runtime: php55

handlers:

- url: /img/(.*\.(gif|png|jpg))
  static_files: img/\1
  upload: img/(.*\.(gif|png|jpg))

- url: /asset/(.*\.(css))
  static_files: asset/\1
  upload: asset/(.*\.(css))

- url: /.*
  script: index.html
